### ISSUE TITLE
Python script fails with uninitialized variable if errors occur or no record is achieved.

### ISSUE THREAD

**Issue by nmcclatchey** [AidenSwayne/QuickFunctions#10]
Variable `comment` is used without definition, in some branches. See https://github.com/AidenSwayne/QuickFunctions/blob/8534c06c021034eb3bdca8555cd9e6b7f3416b8d/utils/run_tests_and_validate_output.py#L108

**Comment by AidenSwayne** [comment]
I’m working on it, along with a lot of other problems! This one should be fixed for now, but I’ll keep it up until I’m certain this is solved.

**Comment by AidenSwayne** [comment]
This is now fixed.
