### ISSUE TITLE
Missing optimizations for C++

### ISSUE THREAD

**Issue by mark2185** [AidenSwayne/QuickFunctions#45]
The default optimization level for GCC is `0` which isn't what you'd normally want when benchmarking. https://github.com/AidenSwayne/QuickFunctions/blob/116139baa8b768dd592f4092e6fd1e930f73b9c4/utils/run_tests_and_validate_output.py#L20

**Comment by AidenSwayne** [comment]
Thanks for the advice! I’m not too familiar with benchmarking, so I’m happy to hear any other suggestions you have. Allowing users to define command-line arguments themselves is something I’d like to add. It seems like a significant security risk, though, so I won’t add them until I have a better understanding of how to securely run code.

**Comment by AidenSwayne** [comment]
I’ve added -O3 to the arguments.
